const AsianCities = [
  { serial: 1, country: "Afghanistan", capital: "Kabul" },
  { serial: 2, country: "Armenia", capital: "Yerevan" },
  { serial: 3, country: "Azerbaijan", capital: "Baku" },
  { serial: 4, country: "Bahrain", capital: "Manama" },
  { serial: 5, country: "Bangladesh", capital: "Dhaka" },
  { serial: 6, country: "Bhutan", capital: "Thimphu" },
  { serial: 7, country: "Brunei", capital: "Bandar Seri Begawan" },
  { serial: 8, country: "Cambodia", capital: "Phnom Penh" },
  { serial: 9, country: "China", capital: "Beijing" },
  { serial: 10, country: "Cyprus", capital: "Nicosia" },
  { serial: 11, country: "East Timor", capital: "Dili" },
  { serial: 12, country: "Georgia", capital: "Tbilisi" },
  { serial: 13, country: "India", capital: "New Delhi" },
  { serial: 14, country: "Indonesia", capital: "Jakarta" },
  { serial: 15, country: "Iran", capital: "Tehran" },
  { serial: 16, country: "Iraq", capital: "Baghdad" },
  { serial: 17, country: "Israel", capital: "Jerusalem" },
  { serial: 18, country: "Japan", capital: "Tokyo" },
  { serial: 19, country: "Jordan", capital: "Amman" },
  { serial: 20, country: "Kazakhstan", capital: "Nur-Sultan" },
  { serial: 21, country: "Kuwait", capital: "Kuwait City" },
  { serial: 22, country: "Kyrgyzstan", capital: "Bishkek" },
  { serial: 23, country: "Laos", capital: "Vientiane" },
  { serial: 24, country: "Lebanon", capital: "Beirut" },
  { serial: 25, country: "Malaysia", capital: "Kuala Lumpur" },
  { serial: 26, country: "Maldives", capital: "Male" },
  { serial: 27, country: "Mongolia", capital: "Ulaanbaatar" },
  { serial: 28, country: "Myanmar", capital: "Naypyidaw" },
  { serial: 29, country: "Nepal", capital: "Kathmandu" },
  { serial: 30, country: "North Korea", capital: "Pyongyang" },
  { serial: 31, country: "Oman", capital: "Muscat" },
  { serial: 32, country: "Pakistan", capital: "Islamabad" },
  { serial: 33, country: "Philippines", capital: "Manila" },
  { serial: 34, country: "Qatar", capital: "Doha" },
  { serial: 35, country: "Saudi Arabia", capital: "Riyadh" },
  { serial: 36, country: "Singapore", capital: "Singapore" },
  { serial: 37, country: "South Korea", capital: "Seoul" },
  { serial: 38, country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte" },
  { serial: 39, country: "State of Palestine", capital: "Jerusalem" },
  { serial: 40, country: "Syria", capital: "Damascus" },
  { serial: 41, country: "Tajikistan", capital: "Dushanbe" },
  { serial: 42, country: "Thailand", capital: "Bangkok" },
  { serial: 43, country: "Turkey", capital: "Ankara" },
  { serial: 44, country: "Turkmenistan", capital: "Ashgabat" },
  { serial: 45, country: "United Arab Emirates", capital: "Abu Dhabi" },
  { serial: 46, country: "Uzbekistan", capital: "Tashkent" },
  { serial: 47, country: "Vietnam", capital: "Hanoi" },
  { serial: 48, country: "Yemen", capital: "Sanaa" },
];

export default AsianCities;
